[platformio]
default_envs = esp32c6

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@7.4.3
  adafruit/Adafruit GFX Library@1.12.6
  olikraus/U8g2_for_Adafruit_GFX@1.8.0

[env:esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
platform_packages =
  framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32/releases/download/3.3.9/esp32-core-3.3.9.tar.xz
board = esp32-c6-devkitc-1
board_build.partitions = max_app_8MB.csv
upload_speed = 460800
build_flags =
  -D EPD_TARGET_BOARD=BOARD_NANO_ESP32_C6
